# Site settings
title: fGrid
description: A responsive and customisable grid system for Sass. Built to be flexible and small and is suitable for a wide range of projects.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fgrid.fullaf.com" # the base hostname & protocol for your site
github_username:  fullaf

# Build settings
markdown: kramdown

sass:
    sass_dir: .
